FilelibDemoBundle_homepage:
    pattern:  /filelib-demo
    defaults: { _controller: FilelibDemoBundle:Default:index }


FilelibDemoBundle_testSuite:
    pattern:  /filelib-demo/test-suite
    defaults: { _controller: FilelibDemoBundle:Default:testSuite }

FilelibDemoBundle_clear:
    pattern:  /filelib-demo/clear
    defaults: { _controller: FilelibDemoBundle:Default:clear }
